version: '3'
services:
  app:
    build: .
    environment:
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_KEY: ${TWITTER_ACCESS_KEY}
      TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET}
  test:
    build: .
    command: python -m unittest
